[package]
name = "othello"
version = "0.1.0"
authors = ["jonas"]

[dependencies]
clippy = "*"
error-chain = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"

[dependencies.gtk]
version = "*"
features = ["v3_10"]
